version: '2.2'

# Define custom network for isolation
networks:
  alma_network:
    driver: bridge
    attachable: true
    labels:
      - description="Isolated network for Alma services"

environment:
  POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
  PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
  RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
  INVENIO_SECRET_KEY=${INVENIO_SECRET_KEY}
  INVENIO_CLI_PATH=${INVENIO_CLI_PATH}

services:

  cache:
    extends:
      file: podman-services.prod.yml
      service: cache
    networks:
      - alma_network
    volumes:
      - redis_data:/data  # Bind mount for critical data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: always
  db:
    extends:
      file: podman-services.prod.yml
      service: db
    networks:
      - alma_network
    volumes:
      - pg_data:/var/lib/postgresql/data  # Bind mount for critical data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    restart: always
  mq:
    extends:
      file: podman-services.prod.yml
      service: mq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - alma_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    restart: always
  search:
    extends:
      file: podman-services.prod.yml
      service: search
    networks:
      - alma_network
    volumes:
      - os_data:/usr/share/opensearch/data  # Bind mount for critical data
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    restart: always
  # Frontend
  frontend:
    extends:
      file: podman-services.prod.yml
      service: frontend
    image: localhost/alma-frontend-prod:1
    networks:
      - alma_network
    volumes:
      - static_data:/opt/invenio/var/instance/static
    depends_on:
      - web-ui
      - web-api
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: always
  # UI Application
  web-ui:
    extends:
      file: podman-services.prod.yml
      service: app
    command: ["uwsgi /opt/invenio/var/instance/uwsgi_ui.ini"]
    image: localhost/alma-app-prod:1
    networks:
      - alma_network
    ports:
      - "5000"
    volumes:
      - static_data:/opt/invenio/var/instance/static
      - uploaded_data:/opt/invenio/var/instance/data
      - archived_data:/opt/invenio/var/instance/archive
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    restart: always

  # API Rest Application
  web-api:
    extends:
      file: podman-services.prod.yml
      service: app
    command: ["uwsgi /opt/invenio/var/instance/uwsgi_rest.ini"]
    image: localhost/alma-app-prod:1
    networks:
      - alma_network
    ports:
      - "5000"
    volumes:
      - uploaded_data:/opt/invenio/var/instance/data
      - archived_data:/opt/invenio/var/instance/archive
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    restart: always

  # Worker
  worker:
    extends:
      file: podman-services.prod.yml
      service: app
    command: ["celery -A invenio_app.celery worker --beat --loglevel=INFO"]
    image: localhost/alma-app-prod:1
    networks:
      - alma_network
    volumes:
      - uploaded_data:/opt/invenio/var/instance/data
    depends_on:
      search:
        condition: service_started
      cache:
        condition: service_started
      db:
        condition: service_started
      mq:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    restart: always


volumes:
  static_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /alma/data/static
    labels:
      - backup=true
      - service=frontend
  uploaded_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /alma/data/uploaded
    labels:
      - backup=true
      - service=web-ui
  archived_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /alma/data/archived
    labels:
      - backup=true
      - service=redis
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /alma/data/redis
    labels:
      - backup=true
      - service=redis
  pg_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /alma/data/postgres
    labels:
      - backup=true
      - service=postgres
  rabbitmq_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /alma/data/rabbitmq
    labels:
      - backup=true
      - service=rabbitmq
  os_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /alma/data/opensearch
    labels:
      - backup=true
      - service=opensearch