version: '2.2'



services:

  cache:
    image: docker.uclv.cu/redis:7
    restart: "unless-stopped"
    read_only: true
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - redis_data:/data

  db:
    image: docker.uclv.cu/postgres:14.13
    restart: "unless-stopped"
    environment:
      - "POSTGRES_USER=alma"
      - "POSTGRES_PASSWORD=alma"
      - "POSTGRES_DB=alma"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alma"]
      interval: 30s
      timeout: 10s
      retries: 3

  mq:
    image: docker.uclv.cu/rabbitmq:3-management
    restart: "unless-stopped"
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # AMQP port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq      
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 30s
      timeout: 10s
      retries: 3

  search:
    image: public.ecr.aws/opensearchproject/opensearch:2.17.1
    restart: "unless-stopped"
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "cluster.blocks.create_index=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  redis_data:
  postgres_data:
  rabbitmq_data:
  opensearch_data:
  static_data:
  uploaded_data:
  archived_data: